Repository instructlab/training, pull requests merged in 2024-11, with the labels that each got.

#312 Adding Dolomite Support and Bringing HF Padding-Free into Performance Parity
  requirements.txt
  src/instructlab/training/main_ds.py
  src/instructlab/training/utils.py
Labels: dependencies

#315 Documentation: Added CHANGELOG.md
  CHANGELOG.md
Labels: documentation, one-approval

#291 Added some safeguards when the necessary imports are not available
  src/instructlab/training/main_ds.py
Labels: documentation, dependencies, CI/CD, testing

#320 deps: change hf accelerate bound, add requirements-hpu.txt
  pyproject.toml
  requirements-cuda.txt
  requirements-hpu.txt
  requirements-rocm.txt
  requirements.txt
Labels: dependencies

#350 Update Dependencies to Move DeepSpeed to CUDA Extras
  requirements-cuda.txt
  requirements-hpu.txt
  requirements-rocm.txt
  requirements.txt
  src/instructlab/training/config.py
  src/instructlab/training/setup_accelerator.py
  src/instructlab/training/utils.py
Labels: dependencies

#356 ci: Upload phase 1 & phase 2 training logs for loss graphs
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
  scripts/create-loss-graph.py
Labels: CI/CD, ci-failure
