Repository instructlab/training, pull requests merged in 2024-12, with the labels that each got.

#361 Add disk check after tests run
  .github/workflows/e2e-nvidia-l4-x1.yml
Labels: CI/CD, one-approval

#357 Updated token masking for new data "unmask" option (for pretraining samples)
  src/instructlab/training/data_process.py
Labels: one-approval

#351 Adjust to slack-github-action 2.0 api changes
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, one-approval

#378 adds pytest to tox via `py3-unit`
  tox.ini
Labels: CI/CD, testing, one-approval
