Repository instructlab/training, pull requests merged in 2024-10, with the labels that each got.

#235 adds Accelerate full-state (opt, lr_sched, params)
  src/instructlab/training/config.py
  src/instructlab/training/main_ds.py
  src/instructlab/training/utils.py
Labels: one-approval

#220 Make data processing optional in run_training()
  README.md
  src/instructlab/training/config.py
  src/instructlab/training/data_process.py
  src/instructlab/training/main_ds.py
Labels: documentation, one-approval

#255 fix: Add explicit flash_attn requirement for ROCm
  requirements-rocm.txt
Labels: dependencies, one-approval

#270 chore: rename 'basic-workflow-tests' to 'e2e-custom'
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD

#277 e2e: replace old small job with new medium job
  .github/mergify.yml
  .github/workflows/e2e-nvidia-a10g-x1.yml
  README.md
Labels: documentation, CI/CD

#279 fix: incorrect label for AWS medium runner
  .github/workflows/e2e-nvidia-a10g-x1.yml
Labels: CI/CD, one-approval

#285 ci: grant HF_TOKEN access to the medium-size E2E CI job
  .github/workflows/e2e-nvidia-a10g-x1.yml
Labels: CI/CD, ci-failure

#290 ci: add large-size E2E CI job
  .github/mergify.yml
  .github/workflows/e2e-nvidia-a10g-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD

#298 fix: add working directory config to steps in large E2E CI job
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD

#299 fix: add remaining missing working directory configs
  .github/workflows/e2e-nvidia-l40s-x4.yml
  README.md
Labels: documentation, CI/CD, one-approval

#302 ci: use org variable for AWS EC2 AMI in E2E CI jobs
  .github/workflows/e2e-nvidia-a10g-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD

#305 ci: convert med E2E CI job to L4 GPU
  .github/mergify.yml
  .github/workflows/e2e-nvidia-l4-x1.yml
  README.md
Labels: documentation, CI/CD, one-approval

#257 Implementing HF Padding-Free and GraniteLM Support
  requirements.txt
  src/instructlab/training/config.py
  src/instructlab/training/data_process.py
  src/instructlab/training/main_ds.py
  src/instructlab/training/token_dataset.py
  src/instructlab/training/utils.py
Labels: dependencies

#280 adds basic smoketests for main_ds and data_process CLI args
  tests/README.md
  tests/smoketest.sh
Labels: testing
