Repository instructlab/training, pull requests merged in 2024-09, with the labels that each got.

#196 ci: add AWS tags to show github ref and PR num for all jobs
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, one-approval

#213 Adding FSDP Support to Training Library
  .pylintrc
  README.md
  requirements.txt
  src/instructlab/training/__init__.py
  src/instructlab/training/chat_templates/ibm_generic_tmpl.py
  src/instructlab/training/chat_templates/mistral_tmpl.py
  src/instructlab/training/config.py
  src/instructlab/training/data_process.py
  src/instructlab/training/main_ds.py
  src/instructlab/training/setup_accelerator.py
  src/instructlab/training/tokenizer_utils.py
  src/instructlab/training/utils.py
Labels: documentation, dependencies, CI/CD, hold

#227 ci: fix lint action
  .github/workflows/lint.yml
  .pylintrc
Labels: CI/CD, one-approval

#218 Docs: Update training README
  README.md
Labels: documentation, ci-failure

#229 changes StreamablePopen to return a process and implement listening
  src/instructlab/training/main_ds.py
  src/instructlab/training/utils.py
Labels: one-approval

#222 switch -T to -a
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, one-approval

#226 github: add stale bot to training repo
  .github/workflows/stale_bot.yml
Labels: CI/CD, one-approval

#231 fix: markdown lint error and mergify bug
  .github/mergify.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
  README.md
Labels: documentation, CI/CD

#232 Fix generic chat template saved to tokenizer for generation
  src/instructlab/training/chat_templates/ibm_generic_tmpl.py
Labels: bug, one-approval
