Repository instructlab/training, pull requests merged in 2024-08, with the labels that each got.

#180 ci: update runner labels to uniquely identify instance sizes
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, one-approval

#189 ci: minor cleanup of E2E job
  .github/mergify.yml
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, one-approval, ci-failure

#191 Fixing e2e to use relative path for working-directory
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, one-approval, ci-failure

#192 Fix linting error and missing quote
  .github/workflows/e2e-nvidia-t4-x1.yml
Labels: CI/CD, ci-failure

#190 Fix typos
  .github/mergify.yml
  .github/workflows/lint.yml
  src/instructlab/training/utils.py
Labels: CI/CD
