Repository instructlab/training, pull requests merged in 2025-06, with the labels that each got.

#588 add DCO.txt
  DCO.txt
  README.md
Labels: documentation

#587 ci: Disable dependabot for pip dependencies
  .github/dependabot.yml
Labels: one-approval

#572 feat: refactor main_ds.py (1/n) Model class
  src/instructlab/training/config.py
  src/instructlab/training/main_ds.py
  src/instructlab/training/model.py
  src/instructlab/training/utils.py
  tests/unit/test_model.py
Labels: testing

#595 ci: do not require DCO job
  .github/mergify.yml
Labels: CI/CD, one-approval

#590 'granite-3.3-2b-instruct' for smoketest; smaller smoke dataset
  tests/smoke/test_train.py
Labels: testing

#581 ci: Cover more test dependencies with pins
  constraints-dev.txt
  requirements-dev.txt
  tox.ini
Labels: dependencies, CI/CD, testing, one-approval

#516 Implicit distributed backend selection
  requirements.txt
  src/instructlab/training/main_ds.py
Labels: dependencies

#599 ci: Fix incorrect indent in workflow steps
  .github/actions/run-e2e/action.yml
Labels: CI/CD, ci-failure

#551 feat: add medium e2e CI job for each PR
  .github/workflows/e2e-nvidia-l40s-x4-sdk.yml
  scripts/test-data/e2e-qna-grounded-employee-skill.yaml
  scripts/test-data/e2e-qna-knowledge-phoenix.yaml
  scripts/test-data/profile-l40s-x4.yaml
  scripts/test-sdk.sh
  scripts/test_sdk.py
Labels: CI/CD, one-approval, ci-failure

#610 test: fix e2e target
  .github/workflows/e2e-nvidia-l40s-x4-sdk.yml
Labels: CI/CD, one-approval

#620 Revert "test: fix e2e target"
  .github/workflows/e2e-nvidia-l40s-x4-sdk.yml
Labels: CI/CD, one-approval

#617 ci: Remove harden-runner steps from jobs
  .github/workflows/actionlint.yml
  .github/workflows/docs.yml
  .github/workflows/e2e-nvidia-l40s-x4-py312.yml
  .github/workflows/e2e-nvidia-l40s-x4-sdk.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
  .github/workflows/lint.yml
  .github/workflows/pypi.yaml
  .github/workflows/smoke-py312.yaml
  .github/workflows/smoke.yaml
  .github/workflows/stale_bot.yml
  .github/workflows/unit.yaml
Labels: CI/CD, one-approval
