Repository instructlab/training, pull requests merged in 2025-04, with the labels that each got.

#443 fix: model.forward now accepts return_dict via kwargs
  src/instructlab/training/utils.py
Labels: one-approval, ci-failure

#424 Adds smoke test workflow and tests
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/smoke.yaml
  .github/workflows/unit.yaml
  pyproject.toml
  requirements-dev.txt
  tests/smoke/test_train.py
  tests/unit/test_init.py
  tox.ini
Labels: dependencies, CI/CD, testing, one-approval

#453 change pytest targets. `test-unit` and `test-smoke` to `unit` and `smoke`
  .github/workflows/smoke.yaml
  tox.ini
Labels: CI/CD, testing, ci-failure

#466 ci: Fix unit test run due to no tests found to execute
  .github/workflows/unit.yaml
Labels: CI/CD, ci-failure

#460 ci: Don't run smoke tests when only irrelevant files are touched
  .github/workflows/smoke.yaml
Labels: CI/CD, ci-failure

#464 ci: don't waste ec2 resources on unit tests
  .github/workflows/unit.yaml
Labels: CI/CD, testing, ci-failure

#469 ci: Trigger unit test run on tox.ini change
  .github/workflows/unit.yaml
Labels: CI/CD, ci-failure

#461 ci: Fix path filter for unit tests for the workflow file
  .github/workflows/unit.yaml
Labels: CI/CD, ci-failure

#468 chore: Don't install pytest dependencies for coverage reports
  tox.ini
Labels: CI/CD, testing, ci-failure

#458 chore: Remove spell checks from the repo
  .github/mergify.yml
  .spellcheck-en-custom.txt
  .spellcheck.yml
  Makefile
  tox.ini
Labels: CI/CD, testing, ci-failure

#475 chore: Don't set ec2_runner_variant for unit tests
  .github/workflows/unit.yaml
Labels: CI/CD, one-approval

#457 Remove CHANGELOG.md
  CHANGELOG.md
Labels: documentation, one-approval, ci-failure

#465 Fix FSDP mixed precision setting and loss w/ accelerate
  src/instructlab/training/config.py
  src/instructlab/training/setup_accelerator.py
Labels: one-approval, ci-failure

#476 fixes non-granite model instantiation with Liger Kernel
  src/instructlab/training/main_ds.py
Labels: ci-failure

#474 ci: Install torch before flash-attn
  .github/workflows/smoke.yaml
Labels: CI/CD, one-approval, ci-failure

#473 ci: Use pull_request as trigger for unit tests
  .github/workflows/unit.yaml
Labels: CI/CD

#472 ci: Run unit tests for all supported python version, 3.11+
  .github/workflows/unit.yaml
  pyproject.toml
Labels: CI/CD, one-approval, ci-failure

#470 chore: Require python3.11+
  pyproject.toml
  requirements.txt
Labels: dependencies, one-approval, ci-failure

#467 chore: Drop pytest-asyncio
  tox.ini
Labels: CI/CD, testing, one-approval, ci-failure

#463 chore: don't trigger unit tests for cuda and rocm requirements changes
  .github/workflows/unit.yaml
Labels: CI/CD, one-approval

#478 ci: Remove workflow that doesn't utilize training library (medium, -mp)
  .github/mergify.yml
  .github/workflows/e2e-nvidia-l4-x1.yml
Labels: CI/CD

#488 Change default internal sharding strategy to HYBRID_SHARD
  src/instructlab/training/main_ds.py
Labels: one-approval, ci-failure

#491 chore: Update the large e2e job to use fallback logic for selecting EC2 instances
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, one-approval

#455 moves deepspeed requirements into their own file; add deepspeed extras
  pyproject.toml
  requirements-cuda.txt
  requirements-deepspeed.txt
Labels: dependencies, one-approval, ci-failure

#501 ci: Fix -sdk fake workflow failure on actionlint
  .github/workflows/e2e-nvidia-l40s-x4-sdk.yml
Labels: CI/CD, one-approval

#499 use instructlab `constraints-dev.txt` in e2e test
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, one-approval, ci-failure

#482 ci: Use tox-current-env to reuse prepared venv with torch
  .github/workflows/smoke.yaml
Labels: CI/CD, ci-failure

#507 fix: extend nccl timeout
  README.md
  src/instructlab/training/main_ds.py
  tox.ini
Labels: documentation, CI/CD, testing, ci-failure
