Repository instructlab/training, pull requests merged in 2025-01, with the labels that each got.

#384 gh/actions unit test workflows
  .github/workflows/unittesting-ci-nvidia.yaml
  src/instructlab/training/config.py
  tests/test_init.py
Labels: CI/CD, testing, ci-failure

#389 changes Fast unit CI runner, m8g->m7i
  .github/workflows/unittesting-ci-nvidia.yaml
Labels: CI/CD, one-approval, ci-failure

#390 chore: Change default temporary write directory in all e2e CI jobs from `tmpfs` to `/home/tmp`
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, ci-failure

#358 feat: retain only last checkpoint directory
  README.md
  src/instructlab/training/config.py
  src/instructlab/training/main_ds.py
  src/instructlab/training/utils.py
Labels: documentation, one-approval

#397 fix: `--keep_last_checkpoint_only` does not accept any values
  src/instructlab/training/main_ds.py
Labels: one-approval, ci-failure

#407 Remove optimum dependency
  requirements-hpu.txt
Labels: dependencies, ci-failure, hold

#409 fixes unit ec2-name
  .github/workflows/unit-tests.yaml
Labels: CI/CD, one-approval

#411 syncs unit testing workflow setup with e2e setup
  .github/workflows/unit-tests.yaml
Labels: CI/CD, one-approval

#415 ci: Add OpenAI keys into CI
  .github/workflows/e2e-nvidia-l4-x1.yml
  .github/workflows/e2e-nvidia-l40s-x4.yml
Labels: CI/CD, ci-failure
