Repository instructlab/training, pull requests merged in 2025-02, with the labels that each got.

#422 Disable medium test by default with older release branches
  .github/workflows/e2e-nvidia-a10g-x1.yml
Labels: CI/CD, one-approval, ci-failure, release-branch

#421 ci: Don't require secrets in medium e2e test
  .github/workflows/e2e-nvidia-l4-x1.yml
Labels: CI/CD, one-approval

#416 Using AutoConfig to load model config file.
  src/instructlab/training/main_ds.py
Labels: ci-failure
