Repository instructlab/training, pull requests merged in 2025-05, with the labels that each got.

#517 deps: Remove caps on ROCm dependencies
  requirements-rocm.txt
Labels: dependencies, one-approval

#519 ci: don't trigger pull_request_target job on its own workflow
  .github/workflows/smoke.yaml
Labels: CI/CD, one-approval

#500 Add general logging implementation
  docs/logging.md
  src/instructlab/training/__init__.py
  src/instructlab/training/async_logger.py
  src/instructlab/training/data_process.py
  src/instructlab/training/ilab_to_sdg.py
  src/instructlab/training/logger.py
  src/instructlab/training/main_ds.py
  src/instructlab/training/multipack_sampler.py
  src/instructlab/training/utils.py
  tests/unit/test_logger.py
  tox.ini
Labels: dependencies, CI/CD, testing

#521 fix: Use default torch timeout for nccl watchdog unless overridden
  src/instructlab/training/main_ds.py
  tests/unit/test_main_ds.py
Labels: testing

#566 adds barriers after checkpoint saving
  src/instructlab/training/main_ds.py
Labels: one-approval, ci-failure

#542 docs: Remove badge for a no longer existing job
  README.md
Labels: documentation

#580 ci: Run jobs on constraints-dev.txt change
  .github/workflows/lint.yml
  .github/workflows/smoke-py312.yaml
  .github/workflows/smoke.yaml
  .github/workflows/unit.yaml
Labels: CI/CD, one-approval

#579 chore: update constraints-dev.txt (2025-05-30)
  constraints-dev.txt
Labels: one-approval
